# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - speakswapserver

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://speakswapregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ee46ba693db24d71a6b6482c411394de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f71c54ab833b46dc8ae55c6e0b87e447 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: speakswapregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee46ba693db24d71a6b6482c411394de }}/speakswap_audioserver:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'speakswapserver'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f06d236bbb794bf1864413cf17ce1115 }}
        images: 'speakswapregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee46ba693db24d71a6b6482c411394de }}/speakswap_audioserver:${{ github.sha }}'